/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package koala.dynamicjava.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 10;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 11;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 12;
  /** RegularExpression Id. */
  int ABSTRACT = 14;
  /** RegularExpression Id. */
  int BOOLEAN = 15;
  /** RegularExpression Id. */
  int BREAK = 16;
  /** RegularExpression Id. */
  int BYTE = 17;
  /** RegularExpression Id. */
  int CASE = 18;
  /** RegularExpression Id. */
  int CATCH = 19;
  /** RegularExpression Id. */
  int CHAR = 20;
  /** RegularExpression Id. */
  int CLASS = 21;
  /** RegularExpression Id. */
  int CONST = 22;
  /** RegularExpression Id. */
  int CONTINUE = 23;
  /** RegularExpression Id. */
  int _DEFAULT = 24;
  /** RegularExpression Id. */
  int DO = 25;
  /** RegularExpression Id. */
  int DOUBLE = 26;
  /** RegularExpression Id. */
  int ELSE = 27;
  /** RegularExpression Id. */
  int EXTENDS = 28;
  /** RegularExpression Id. */
  int FALSE = 29;
  /** RegularExpression Id. */
  int FINAL = 30;
  /** RegularExpression Id. */
  int FINALLY = 31;
  /** RegularExpression Id. */
  int FLOAT = 32;
  /** RegularExpression Id. */
  int FOR = 33;
  /** RegularExpression Id. */
  int GOTO = 34;
  /** RegularExpression Id. */
  int IF = 35;
  /** RegularExpression Id. */
  int IMPLEMENTS = 36;
  /** RegularExpression Id. */
  int IMPORT = 37;
  /** RegularExpression Id. */
  int INSTANCEOF = 38;
  /** RegularExpression Id. */
  int INT = 39;
  /** RegularExpression Id. */
  int INTERFACE = 40;
  /** RegularExpression Id. */
  int LONG = 41;
  /** RegularExpression Id. */
  int NATIVE = 42;
  /** RegularExpression Id. */
  int NEW = 43;
  /** RegularExpression Id. */
  int NULL = 44;
  /** RegularExpression Id. */
  int PACKAGE = 45;
  /** RegularExpression Id. */
  int PRIVATE = 46;
  /** RegularExpression Id. */
  int PROTECTED = 47;
  /** RegularExpression Id. */
  int PUBLIC = 48;
  /** RegularExpression Id. */
  int RETURN = 49;
  /** RegularExpression Id. */
  int SHORT = 50;
  /** RegularExpression Id. */
  int STATIC = 51;
  /** RegularExpression Id. */
  int SUPER = 52;
  /** RegularExpression Id. */
  int SWITCH = 53;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 54;
  /** RegularExpression Id. */
  int THIS = 55;
  /** RegularExpression Id. */
  int THROW = 56;
  /** RegularExpression Id. */
  int THROWS = 57;
  /** RegularExpression Id. */
  int TRANSIENT = 58;
  /** RegularExpression Id. */
  int TRUE = 59;
  /** RegularExpression Id. */
  int TRY = 60;
  /** RegularExpression Id. */
  int VOID = 61;
  /** RegularExpression Id. */
  int VOLATILE = 62;
  /** RegularExpression Id. */
  int WHILE = 63;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 64;
  /** RegularExpression Id. */
  int LONG_LITERAL = 65;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 66;
  /** RegularExpression Id. */
  int HEX_LITERAL = 67;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 68;
  /** RegularExpression Id. */
  int FLOAT_LITERAL = 69;
  /** RegularExpression Id. */
  int DOUBLE_LITERAL = 70;
  /** RegularExpression Id. */
  int EXPONENT = 71;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 72;
  /** RegularExpression Id. */
  int STRING_LITERAL = 73;
  /** RegularExpression Id. */
  int IDENTIFIER = 74;
  /** RegularExpression Id. */
  int LETTER = 75;
  /** RegularExpression Id. */
  int DIGIT = 76;
  /** RegularExpression Id. */
  int LPAREN = 77;
  /** RegularExpression Id. */
  int RPAREN = 78;
  /** RegularExpression Id. */
  int LBRACE = 79;
  /** RegularExpression Id. */
  int RBRACE = 80;
  /** RegularExpression Id. */
  int LBRACKET = 81;
  /** RegularExpression Id. */
  int RBRACKET = 82;
  /** RegularExpression Id. */
  int SEMICOLON = 83;
  /** RegularExpression Id. */
  int COMMA = 84;
  /** RegularExpression Id. */
  int DOT = 85;
  /** RegularExpression Id. */
  int ASSIGN = 86;
  /** RegularExpression Id. */
  int GREATER_THAN = 87;
  /** RegularExpression Id. */
  int LESS = 88;
  /** RegularExpression Id. */
  int BANG = 89;
  /** RegularExpression Id. */
  int TILDE = 90;
  /** RegularExpression Id. */
  int HOOK = 91;
  /** RegularExpression Id. */
  int COLON = 92;
  /** RegularExpression Id. */
  int EQUAL = 93;
  /** RegularExpression Id. */
  int LESS_OR_EQUAL = 94;
  /** RegularExpression Id. */
  int GREATER_OR_EQUAL = 95;
  /** RegularExpression Id. */
  int NOT_EQUAL = 96;
  /** RegularExpression Id. */
  int CONDITIONAL_OR = 97;
  /** RegularExpression Id. */
  int CONDITIONAL_AND = 98;
  /** RegularExpression Id. */
  int INCREMENT = 99;
  /** RegularExpression Id. */
  int DECREMENT = 100;
  /** RegularExpression Id. */
  int PLUS = 101;
  /** RegularExpression Id. */
  int MINUS = 102;
  /** RegularExpression Id. */
  int STAR = 103;
  /** RegularExpression Id. */
  int SLASH = 104;
  /** RegularExpression Id. */
  int BITWISE_AND = 105;
  /** RegularExpression Id. */
  int BITWISE_OR = 106;
  /** RegularExpression Id. */
  int XOR = 107;
  /** RegularExpression Id. */
  int REMAINDER = 108;
  /** RegularExpression Id. */
  int LEFT_SHIFT = 109;
  /** RegularExpression Id. */
  int RIGHT_SIGNED_SHIFT = 110;
  /** RegularExpression Id. */
  int RIGHT_UNSIGNED_SHIFT = 111;
  /** RegularExpression Id. */
  int PLUS_ASSIGN = 112;
  /** RegularExpression Id. */
  int MINUS_ASSIGN = 113;
  /** RegularExpression Id. */
  int STAR_ASSIGN = 114;
  /** RegularExpression Id. */
  int SLASH_ASSIGN = 115;
  /** RegularExpression Id. */
  int AND_ASSIGN = 116;
  /** RegularExpression Id. */
  int OR_ASSIGN = 117;
  /** RegularExpression Id. */
  int XOR_ASSIGN = 118;
  /** RegularExpression Id. */
  int REMAINDER_ASSIGN = 119;
  /** RegularExpression Id. */
  int LEFT_SHIFT_ASSIGN = 120;
  /** RegularExpression Id. */
  int RIGHT_SIGNED_SHIFT_ASSIGN = 121;
  /** RegularExpression Id. */
  int RIGHT_UNSIGNED_SHIFTASSIGN = 122;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 2;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "\"#\"",
    "<token of kind 8>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 13>",
    "\"abstract\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "<INTEGER_LITERAL>",
    "<LONG_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOAT_LITERAL>",
    "<DOUBLE_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
  };

}
